config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles
  devise_scope :user do
   get "sign_up", to: "devise/registrations#new"
   get "log_in", to: "devise/sessions#new"
   get "log_out", to: "devise/sessions#destroy"
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @article = Article.find(params[:id])
  end

  def show
    @article = Article.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    Delayed::Job.enqueue CrawlJob.new
    @articles = Article.all
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/show.html.erb
<%= render 'partials/article' %>

app/views/home/index.html.erb
<div id="wrapper">
  <div id="navigation-sidebar">
      <ul>
          <li>Associated Press</li>
          <li>Bloomberg</li>
          <li>Economist</li>
          <li>Reuters</li>
      </ul>
      <% if !@subscriptions.nil? %>
        <% @subscriptions.each do |subscrption| %>
            <%= link_to subscription.name, articles_path(subscription.id) %>
        <% end %>
      <% end %>
  </div>

  <div id="header"></div>

  <div id="main-content">
      <div id="headlines" style="display:inline; width:30%; height: 90px;">
          <% @articles.where(headline: 1).take(3).each do |headline| %>
              <div class="headline">
                  <img src='#{headline.image}', alt="woops!" >
                  <h2 style="text-align:center; color:black; border-bottom: solid thin;"><%= link_to strip_tags(headline.title), article_path(headline.id) %></h2>
                  <%# <p style="width: 90%; text-align:left; margin:auto"><%= headline.preview -%></p>
              </div>
          <% end %>
      </div>
      <% @articles.where(headline: 0).take(20).each do |article| %>
          <div class="article" style="width:80%; margin:auto;">
            <img src="#{article.source_img}", alt="woops!">
            <h2 style="text-align:center; color:black; border-bottom: solid thin;"><%= link_to strip_tags(article.title), article_path(article.id) %></h2>
            <p style="width: 90%; text-align:left; margin:auto"><%# article.preview -%></p>
          </div>
      <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/partials/_article.html.erb
<div id="headline" style="width:80%; margin:auto; border:solid thin green;">
  <%= strip_tags(@article.title) %>
</div>

<div id="article-body" style="width:80%; margin:auto; border:solid thin;">
  <%= strip_tags(@article.content) %>
</div>

app/views/partials/_article_index.html.erb
<div id="articles">

  <h2>Articles One</h2>
  <% if !@articles.nil? %>
    <% @articles.each do |article| %>
      <div class="article">
        <h2 style="color:green;"><%= link_to strip_tags("#{article.title}"), articles_path(id: article.id) %></h2>
        <a href='<%= article.url %>'><%= strip_tags(article.url) %></a>
        <p><%= strip_tags(article.content) %></p>
      </div>
    <% end %>
  <% end %>
</div>

app/views/partials/_navigation_sidebar.html.erb
<div id="navigation-sidebar">
  <ol>
    <li>Item 1</li>
    <li>Item 2</li>
    <li>Item 3</li>
    <li>Item 4</li>
  </ol>
</div>

app/views/partials/_sign_in_sign_up.html.erb
<div id="sign_in_sign_up">
  <%= link_to "sign in", new_user_session_url %>
  <%= link_to "sign up", new_user_registration_url %>
</div>